use std::error::Error;

pub fn run() -> Result<(), Box<dyn Error>> {
    generate_report();
    Ok(())
}

fn generate_report() {
    
}